// TD5/auth-system-angular/src/app/components/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css'],
  standalone: true,
  imports: [CommonModule]
})
export class DashboardComponent implements OnInit {
  username: string = '';
  
  constructor(private router: Router) {}
  
  ngOnInit() {
    // Check if user is logged in
    const currentUser = localStorage.getItem('currentUser');
    if (!currentUser) {
      this.router.navigate(['/login']);
      return;
    }
    
    // Get user data
    try {
      const userData = JSON.parse(currentUser);
      this.username = userData.username;
    } catch (error) {
      console.error('Error parsing user data', error);
      this.logout();
    }
  }
  
  logout() {
    // Clear local storage
    localStorage.removeItem('currentUser');
    // Navigate to login
    this.router.navigate(['/login']);
  }
}
<div class="dashboard-container">
    <h2>Welcome, {{ username }}!</h2>
    
    <div class="dashboard-content">
      <p>You are now logged in to your dashboard.</p>
      <p>This is a secure area available only to authenticated users.</p>
    </div>
    
  </div>

// TD5/auth-system-react/src/components/Dashboard/Dashboard.js
import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import "./Dashboard.css";

const Dashboard = () => {
  const [user, setUser] = useState(null);
  const navigate = useNavigate();

  useEffect(() => {
    const currentUser = localStorage.getItem("currentUser");
    if (!currentUser) {
      navigate("/login");
      return;
    }

    try {
      const userData = JSON.parse(currentUser);
      setUser(userData);
    } catch (error) {
      console.error("Error parsing user data", error);
      localStorage.removeItem("currentUser");
      navigate("/login");
    }
  }, [navigate]);

  if (!user) {
    return <div>Loading...</div>;
  }

  return (
    <div className="dashboard-container">
      <h2>Welcome, {user.username}!</h2>

      <div className="dashboard-content">
        <p>You are now logged in to your dashboard.</p>
        <p>This is a secure area available only to authenticated users.</p>
      </div>
    </div>
  );
};

export default Dashboard;
