// TD5/auth-system-angular/src/app/components/signup/signup.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css'],
  standalone: true,
  imports: [FormsModule, CommonModule, RouterModule]
})
export class SignupComponent {
  username: string = '';
  email: string = '';
  password: string = '';
  errorMessage: string = '';
  
  constructor(private http: HttpClient, private router: Router) {}
  
  onSubmit() {
    // Validate form
    if (!this.username || !this.email || !this.password) {
      this.errorMessage = 'All fields are required';
      return;
    }
    
    // Create user object
    const user = {
      username: this.username,
      email: this.email,
      password: this.password
    };
    
    // Send to JSON server
    this.http.post('http://localhost:3000/users', user)
      .subscribe({
        next: (response) => {
          console.log('User registered successfully', response);
          this.router.navigate(['/login']);
        },
        error: (error) => {
          console.error('Registration failed', error);
          this.errorMessage = 'Registration failed. Please try again.';
        }
      });
  }
}
<div class="signup-container">
    <h2>Sign Up</h2>
    
    <form (ngSubmit)="onSubmit()">
      <div class="form-group">
        <label for="username">Username</label>
        <input id="username" type="text" [(ngModel)]="username" name="username" required>
      </div>
      
      <div class="form-group">
        <label for="email">Email</label>
        <input id="email" type="email" [(ngModel)]="email" name="email" required>
      </div>
      
      <div class="form-group">
        <label for="password">Password</label>
        <input id="password" type="password" [(ngModel)]="password" name="password" required>
      </div>
      
      <div class="error-message" *ngIf="errorMessage">
        {{ errorMessage }}
      </div>
      
      <button type="submit">Sign Up</button>
      
      <div class="login-link">
        Already have an account? <a routerLink="/login">Login</a>
      </div>
    </form>
  </div>

// TD5/auth-system-react/src/components/Signup/Signup.js
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Formik, Form, Field, ErrorMessage } from "formik";
import * as Yup from "yup";
import { registerUser } from "../../services/api";
import "./Signup.css";

const SignupSchema = Yup.object().shape({
  username: Yup.string().required("Username is required"),
  email: Yup.string().email("Invalid email").required("Email is required"),
  password: Yup.string()
    .min(6, "Password must be at least 6 characters")
    .required("Password is required"),
});

const Signup = () => {
  const navigate = useNavigate();
  const [error, setError] = useState("");

  const handleSubmit = async (values, { setSubmitting }) => {
    try {
      await registerUser(values);
      navigate("/login");
    } catch (err) {
      setError("Registration failed. Please try again.");
      console.error("Error during registration:", err);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="signup-container">
      <h2>Sign Up</h2>
      <Formik
        initialValues={{ username: "", email: "", password: "" }}
        validationSchema={SignupSchema}
        onSubmit={handleSubmit}
      >
        {({ isSubmitting }) => (
          <Form>
            <div className="form-group">
              <label htmlFor="username">Username</label>
              <Field type="text" id="username" name="username" />
              <ErrorMessage name="username" component="div" className="error" />
            </div>

            <div className="form-group">
              <label htmlFor="email">Email</label>
              <Field type="email" id="email" name="email" />
              <ErrorMessage name="email" component="div" className="error" />
            </div>

            <div className="form-group">
              <label htmlFor="password">Password</label>
              <Field type="password" id="password" name="password" />
              <ErrorMessage name="password" component="div" className="error" />
            </div>

            {error && <div className="error-message">{error}</div>}

            <button type="submit" disabled={isSubmitting}>
              {isSubmitting ? "Signing up..." : "Sign Up"}
            </button>

            <div className="login-link">
              Already have an account? <a href="/login">Login</a>
            </div>
          </Form>
        )}
      </Formik>
    </div>
  );
};

export default Signup;
