// TD5/angular-auth-system/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
  standalone: true,
  imports: [FormsModule, CommonModule, RouterModule]
})
export class LoginComponent {
  username: string = '';
  password: string = '';
  errorMessage: string = '';
  
  constructor(private http: HttpClient, private router: Router) {}
  
  onSubmit() {
    // Simple validation
    if (!this.username || !this.password) {
      this.errorMessage = 'Username and password are required';
      return;
    }
    
    // Check user credentials against the database
    this.http.get<any[]>(`http://localhost:3000/users?username=${this.username}`)
      .subscribe({
        next: (users) => {
          if (users.length > 0 && users[0].password === this.password) {
            // Store user info in localStorage
            localStorage.setItem('currentUser', JSON.stringify(users[0]));
            
            // Dispatch a storage event to notify other components
            window.dispatchEvent(new Event('storage'));
            
            // Navigate to dashboard
            this.router.navigate(['/dashboard']);
          } else {
            this.errorMessage = 'Invalid username or password';
          }
        },
        error: (error) => {
          console.error('Login failed', error);
          this.errorMessage = 'Login failed. Please try again.';
        }
      });
  }
}
<div class="login-container">
    <h2>Login</h2>
    
    <form (ngSubmit)="onSubmit()">
      <div class="form-group">
        <label for="username">Username</label>
        <input id="username" type="text" [(ngModel)]="username" name="username" required>
      </div>
      
      <div class="form-group">
        <label for="password">Password</label>
        <input id="password" type="password" [(ngModel)]="password" name="password" required>
      </div>
      
      <div class="error-message" *ngIf="errorMessage">
        {{ errorMessage }}
      </div>
      
      <button type="submit">Login</button>
      
      <div class="signup-link">
        Don't have an account? <a routerLink="/signup">Sign Up</a>
      </div>
    </form>
  </div>

// TD5/auth-system-react/src/components/Login/Login.js
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Formik, Form, Field, ErrorMessage } from "formik";
import * as Yup from "yup";
import { loginUser } from "../../services/api";
import "./Login.css";

const LoginSchema = Yup.object().shape({
  username: Yup.string().required("Username is required"),
  password: Yup.string().required("Password is required"),
});

const Login = () => {
  const navigate = useNavigate();
  const [error, setError] = useState("");

  const handleSubmit = async (values, { setSubmitting }) => {
    try {
      const response = await loginUser(values.username);
      const users = response.data;

      if (users.length > 0 && users[0].password === values.password) {
        localStorage.setItem("currentUser", JSON.stringify(users[0]));
        navigate("/dashboard");
      } else {
        setError("Invalid username or password");
      }
    } catch (err) {
      setError("Login failed. Please try again.");
      console.error("Error during login:", err);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="login-container">
      <h2>Login</h2>
      <Formik
        initialValues={{ username: "", password: "" }}
        validationSchema={LoginSchema}
        onSubmit={handleSubmit}
      >
        {({ isSubmitting }) => (
          <Form>
            <div className="form-group">
              <label htmlFor="username">Username</label>
              <Field type="text" id="username" name="username" />
              <ErrorMessage name="username" component="div" className="error" />
            </div>

            <div className="form-group">
              <label htmlFor="password">Password</label>
              <Field type="password" id="password" name="password" />
              <ErrorMessage name="password" component="div" className="error" />
            </div>

            {error && <div className="error-message">{error}</div>}

            <button type="submit" disabled={isSubmitting}>
              {isSubmitting ? "Logging in..." : "Login"}
            </button>

            <div className="login-link">
              Don't have an account? <a href="/signup">Sign Up</a>
            </div>
          </Form>
        )}
      </Formik>
    </div>
  );
};

export default Login;
